kimai:
    invoice:
        renderer:
            Short: 'Keleo\KimaiInvoice\Controller\InvoiceRendererController::shortAction'
        number_generator:
            Random: 'Keleo\KimaiInvoice\Invoice\RandomNumberGenerator'
